### ISSUE TITLE
Xcode8报错使用swift2.3

### ISSUE THREAD

**Issue by dadpp** [banxi1988/BXForm#1]
在AlertPresentationController类中Initializer does not override a designated initializer from its superclass

**Comment by codetalks-new** [comment]
@BaiCanLin  好的我等会看看. 现在正在处理 3.0 的支持 哎呀, 我的这个库居然还有其他人用.

**Comment by codetalks-new** [comment]
@BaiCanLin 建议你直接修改 项目中的 代码. Pod 的本地库文件也可以直接编辑.
如果你使用 Swift 3 的话,我刚才已经迁移上传更新了.
